version: '2'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "weather"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"